apiVersion: v1
kind: Pod  #Tipo de objeto

metadata:
  name: mysql
  labels:
    app: web-wordpress
    microservice: mysql
    version: v1
spec:    #Aspectos técnicos
  containers:
    - name: mysql
      image: mysql:8.3.0
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: asd123
        - name: MYSQL_DATABASE
          value: wordpress_db
        - name: MYSQL_USER
          value: wordpress_user
        - name: MYSQL_PASSWORD
          value: asdf1234
      ports:
        - containerPort: 3306