apiVersion: v1
kind: Service  #Tipo de objeto

metadata:
  name: wordpress-service
  labels:
    app: web-wordpress
    version: v1
spec:    #Aspectos técnicos
  type: LoadBalancer
  selector:
    microservice: wordpress
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80